#\u914D\u7F6E\u6570\u636E\u6E90
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///springxm?serverTimezone=UTC
    username: root
    password: 123
  #thymeleafpe
  thymeleaf:
    encoding: UTF-8
    #\u5F00\u53D1\u65F6\u5173\u95ED\u7F13\u5B58(\u6A21\u677F\u53EA\u52A0\u8F7D\u4E00\u6B21),\u4E0D\u7136\u6CA1\u6CD5\u770B\u5230\u5B9E\u65F6\u9875\u9762(\u6539\u4E86html\u8981\u91CD\u542F)
    cache: false
    mode: HTML
    prefix: classpath:templates/
    suffix: .html
#MyBatis\u914D\u7F6E
mybatis:
  type-aliases-package: com.cssl.pojo
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    #\u4E8C\u7EA7\u7F13\u5B58
    cache-enabled: true
#\u5206\u9875\u8BBE\u7F6E
pagehelper:
  reasonable: true
  page-size-zero: true
